version: "3"

services:
  vote:
    build: ./vote
    command: python app.py
    volumes:
     - ./vote:/app
    ports:
      - "5000:80"
    networks:
      - frontend

  result:
    image: dockersamples/examplevotingapp_result:before
    ports:
      - "5001:80"
    networks:
      - backend

  worker:
    image: dockersamples/examplevotingapp_worker
    networks:
      - frontend
      - backend

  redis:
    image: redis:alpine
    ports: 
      - "6379"
    networks:
      - frontend

  db:
    image: postgres:9.4
    networks:
      - backend

networks:
  frontend:
  backend: