version: "3"
services:

  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - frontend
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  db:
    image: postgres:9.4
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    deploy:
      placement:
        constraints: [node.role == manager]
  vote:
    build: ./vote
    ports:
      - "80"
    networks:
      - frontend
      - traefik-net
    depends_on:
      - redis
    deploy:
      labels:
        - "traefik.port=80"
        - "traefik.docker.network=traefik-net"
      replicas: 2
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure
  result:
    image: dockersamples/examplevotingapp_result:before
    ports:
      - "80"
    networks:
      - backend
      - traefik-net
    depends_on:
      - db
    deploy:
      labels:
        - "traefik.docker.network=traefik-net"
        - "traefik.port=80"
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  worker:
    image: dockersamples/examplevotingapp_worker
    networks:
      - frontend
      - backend
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=VOTING]
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.role == manager]

networks:
  traefik-net:
    external:
      name: traefik-net
  frontend:
  backend:
  
volumes:
  db-data:
